[TCP]
server = yaamp.com
port = 6453
password = tu8tu5

[SQL]
host = yaampdb
database = yaamp
username = root
password = patofpaq

[STRATUM]
algo = ethash
difficulty = 0.1
diff_min = 0.05
diff_max = 8192
max_ttf = 50000

[WALLETS]
include = VBC
